### ISSUE TITLE
the connectors are hard to use

### ISSUE THREAD

**Issue by ghost** [evhart/preserve#1]
Ive looked at the code for sometime and I can't figure out how to import the connectors, they get passed around so much its very confusing, I wonder if you use the init file for the preserve package and import in the classes in from the connectors package.

**Comment by evhart** [comment]
You have two methods for using a connector. You can either:
1) Use a JDBC style string (recommended)  using "from_uri", or;
2) Create a connection manually using the "open" method.

You should not call Preserve or the connectors directly.
The "Preserve()" singleton object loads automatically the different connectors from "preserve.connectors" or from package extensions (untested). "Preserve()" is called by the  "from_uri" and "open" methods.
